export const orderDetail = {
  "orderId": 160649,
  "dateCreated": "2025-09-09T14:06:34.107",
  "email": "marco.guzman@blacklandtransport.com",
  "firstName": "Marco",
  "lastName": "Guzman",
  "phone": "(305) 450-7384",
  "newsletter": null,
  "device": 0,
  "paidByCheck": false,
  "repUserId": null,
  "couponCode": "",
  "customCouponCode": "",
  "customCouponDiscount": null,
  "payPartner": "",
  "sqToken": "",
  "payerId": "",
  "avsResponse": "",
  "authorizationCode": "",
  "transactionId": "",
  "subTotal": 0,
  "shipping": 80,
  "tax": 100,
  "grandTotal": 0,
  "discount": 1125,
  "protectionPlanOrder": 2,
  "protectionPlanOrderPrice": 200,
  "status": "Shipped",
  "shippingId": null,
  "ccCode": "SQ",
  "shippingFirstName": "Marco",
  "shippingLastName": "Guzman",
  "shippingStreet": "1443 Oak Marsh Street",
  "shippingStreet2": "",
  "shippingCity": "Davenport",
  "shippingState": "FL",
  "shippingZipCode": "33837",
  "shippingCountry": "US",
  "shippingCompanyName": "",
  "billingFirstName": "Marco",
  "billingLastName": "Guzman",
  "billingStreet": "1443 Oak Marsh Street",
  "billingStreet2": "",
  "billingCity": "Davenport",
  "billingState": "FL",
  "billingZipCode": "33837",
  "billingCountry": "US",
  "billingCompanyName": "",
  "gatewayComments": "Trade show discount\nTamir 323-570-0588",
  "cartItems": [
    {
      "orderItemId": 922555,
      "productId": 3646,
      "quantity": 3,
      "productIsParent": null,
      "protectionPlanProduct": 0,
      "protectionPlanProductPrice": 0,
      "cartOptionId": null,
      "productPrice": 999.99,
      "productName": "Delivery Truck 1080P Digital Wireless Camera System with 3 Cameras (V3)",
      "sku": "SKU15883",
      "isMainProduct": true,
      "defaultImage": "638452490207005553.jpg",
      "category": {
        "categoryId": 146,
        "categoryName": "FedEx Vehicles"
        },
      "components": [
        {
          "componentProductId": 3580,
          "componentSKU": "SKU18392",
          "componentName": "7-Inch Digital Wireless Rear View Monitor, Commercial Grade (V3)",
          "componentPrice": 349.99,
          "componentDefaultImage": "638324408437490723.jpg",
          "componentUniqueName": "digital-wireless-7-inch-lcd-rear-view-monitor-v3",
          "componentListPrice": 379.99,
          "componentAverageRating": 4.5,
          "componentNumberOfRatings": 72
        },
        {
          "componentProductId": 3581,
          "componentSKU": "SKU34190",
          "componentName": "1080P Digital Wireless RV Backup Camera with 300ft Range (V3)",
          "componentPrice": 299.99,
          "componentDefaultImage": "638326198169745058.jpg",
          "componentUniqueName": "digital-wireless-rv-backup-camera-300ft-range-v3",
          "componentListPrice": 379.99,
          "componentAverageRating": 4.6,
          "componentNumberOfRatings": 35
        },
        {
          "componentProductId": 3696,
          "componentSKU": "SKU52561",
          "componentName": "2 Digital Wireless Premium 1080P Side Cameras with Driver and Passenger sides 2025 (V3)",
          "componentPrice": 574.99,
          "componentDefaultImage": "638687312255960489.jpg",
          "componentUniqueName": "2-Digital-built-in-premium-side-rv-camera-wireless-v3-2025",
          "componentListPrice": 749.99,
          "componentAverageRating": 4.56666666666667,
          "componentNumberOfRatings": 30
        }
      ],
      "options": [
        {
          "optionId": 6656,
          "optionsCategoryId": 631,
          "optionSKU": "SKU18392",
          "optionName": "7-Inch Digital Monitor DVR V3 (SKU18392U)",
          "optionPrice": 224.99,
          "optionImage": "7-inch_Digital_DVR_V3.png",
          "optionDefaultImage": "638694313164504774.jpg"
        }
      ],
      "videos": [
        {
          "id": 639,
          "title": "How to Pair TadiBrothers Version 3 Digital Wireless Cameras – Step-by-Step Guide",
          "youTubeCode": "Pasej8IIkp0",
          "displayOrder": 6,
          "url": "Pairing-Digital-Wireless-Camera-(V3)",
          "description": "In this comprehensive video tutorial, Tamir from TadiBrothers walks you through the step-by-step process of pairing the new Version 3 Digital Wireless Cameras. With upgraded features like integrated DVRs, square buttons, and blue plungers for pairing, these cameras are designed for maximum efficiency. \r\n\r\nLearn how to connect the antenna, power up your monitor using a 12V connection, and pair your cameras to the desired channels. Tamir explains both the shortcut and menu-based pairing methods, making it simple for you to get your RV, license, or side cameras up and running.\r\n\r\nYou’ll discover helpful tips, like identifying indicator lights to confirm power and using the split-screen mode to view multiple cameras simultaneously. Plus, Tamir provides troubleshooting advice and a quick overview of the mute function to eliminate microphone feedback. Whether you’re a first-time user or upgrading from a previous version, this video ensures a seamless setup experience.\r\n\r\nFor personalized support, TadiBrothers’ U.S.-based tech team is just a call away at 866-966-5550. Watch now and see how easy it is to pair your Version 3 wireless cameras!",
          "isFeatured": false,
          "metaDescription": "Learn how to pair TadiBrothers Version 3 Wireless Cameras with this step-by-step video guide. Features include DVRs, split-screen mode & expert tips. Call 866-966-5550 for support!",
          "h1": "Pairing TadiBrothers Version 3 Wireless Cameras Made Easy",
          "canon": null,
          "enableCanon": null,
          "filter": "5,6,7,9",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        },
        {
          "id": 640,
          "title": "Master Split Screen Settings on TadiBrothers Digital 3 Systems | Expert Guide",
          "youTubeCode": "5FdVw9Hgu78",
          "displayOrder": 6,
          "url": "Split-screen-setting-for-the-Digital-backup-camera-By-TadiBrothers-(V3)",
          "description": "Welcome to TadiBrothers! In this video, Tamir walks you through the split-screen settings for the Digital 3 version of our systems, helping you achieve the perfect camera view for your needs. If your system features a blue cube or plunger on the camera, you’re in the right place!\r\n\r\nTamir demonstrates how to customize your split-screen views by accessing the menu and selecting different modes. Learn how to set up your channels for 3-camera or 4-camera configurations and discover features like the HV view, quad view, and side-by-side layouts. Whether you’re pairing new cameras or optimizing your existing setup, this step-by-step guide ensures you get the most out of your TadiBrothers system.\r\n\r\nThis tutorial highlights the flexibility and user-friendly design of our backup camera systems, empowering you to adjust your views to suit any scenario. Have questions? Our U.S.-based support team is here for you at 866-966-5550, and Tamir himself is happy to assist.\r\n\r\nSubscribe for more helpful guides from TadiBrothers—where “we back you up” with innovative solutions and unbeatable customer service!",
          "isFeatured": false,
          "metaDescription": "Learn how to customize split-screen settings on the TadiBrothers Digital 3 system. Watch step-by-step instructions and optimize your camera views. Call 866-966-5550 for support!",
          "h1": "How to Customize Split Screen Settings on Your TadiBrothers Digital 3 System",
          "canon": null,
          "enableCanon": null,
          "filter": "5,6,7,9",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        },
        {
          "id": 641,
          "title": "Complete Guide to Mobile DVR Settings for TadiBrothers Digital Wireless System V3",
          "youTubeCode": "rETWJ-II7x0",
          "displayOrder": 6,
          "url": "Mobile-DVR-Setting-and-Playback-for-the-Digital-Wireless-Backup-Cameras-System-by-TadiBrothers-(V3)",
          "description": "In this comprehensive guide, Tamir from TadiBrothers walks you through the settings and features of the Mobile DVR included in the Digital Wireless System V3. Identified by the blue square on the monitor, RV camera, and license camera, this system is designed for seamless recording and playback. Learn how to check DVR modes, install and format SD cards, and activate loop recording, ensuring your system continuously overwrites old recordings to save space.\r\n\r\nTamir also explains how to customize recording intervals (1, 3, or 5 minutes) and highlights the system’s unique ability to record each channel individually. This allows for detailed event tracking, whether you're reviewing footage from an RV, side, or license camera.\r\n\r\nPlayback options are versatile—you can view recordings directly on the monitor or extract the memory stick to a computer. The guide also provides troubleshooting tips and ensures users get the most out of their Mobile DVR.\r\n\r\nFor further assistance, the TadiBrothers American-based tech team is available at 866-966-5550. With these easy steps, you’ll master the features of your Digital Wireless System V3 and enjoy peace of mind on every journey. \"We back you up!\"\r\n\r\nLet me know if you'd like any adjustments or additional elements!",
          "isFeatured": false,
          "metaDescription": "Step-by-step guide to setting up your TadiBrothers Mobile DVR on the Digital Wireless System V3. Learn about loop recording, formatting SD cards, and playback features.",
          "h1": "How to Use and Optimize Your Mobile DVR on TadiBrothers Digital Wireless System V3",
          "canon": null,
          "enableCanon": null,
          "filter": "5,6,7,9",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        }
      ]
    },
    {
      "orderItemId": 922556,
      "productId": 3656,
      "quantity": 3,
      "productIsParent": null,
      "protectionPlanProduct": 0,
      "protectionPlanProductPrice": 0,
      "cartOptionId": null,
      "productPrice": 499.99,
      "productName": "Commercial Grade Parking Backup Sensors for Box Trucks and Delivery Vans",
      "sku": "SKU85258",
      "isMainProduct": false,
      "defaultImage": "638502497256225996.jpg",
      "category": {
        "categoryId": 25,
        "categoryName": "Parking Sensors"
      },
      "components": [
         {
          "componentProductId": 3691,
          "componentSKU": "SKU52561",
          "componentName": "2 Digital Wireless Premium 1080P Side Cameras with Driver and Passenger sides 2025 (V3)",
          "componentPrice": 374.99,
          "componentDefaultImage": "638687312255960489.jpg",
          "componentUniqueName": "2-Digital-built-in-premium-side-rv-camera-wireless-v3-2025",
          "componentListPrice": 749.99,
          "componentAverageRating": 2.56666666666667,
          "componentNumberOfRatings": 32
        }
      ],
      "options": [
        {
          "optionId": 6622,
          "optionsCategoryId": 632,
          "optionSKU": "SKU18391",
          "optionName": "7-Inch Digital Monitor DVR V3 (SKU18392U)",
          "optionPrice": 543.99,
          "optionImage": "7-inch_Digital_DVR_V3.png",
          "optionDefaultImage": "638452490207005553.jpg"
        }
      ],
      "videos": [
        {
          "id": 770,
          "title": "🚛 Commercial-Grade Parking Backup Sensors – Perfect for Vans, RVs & Trailers!",
          "youTubeCode": "UzAPU5AxBtY",
          "displayOrder": 6,
          "url": "commercial-parking-backup-sensors",
          "description": "🔹 Enhance your safety with the TadiBrothers Commercial-Grade Parking Sensor System! 🚛 Whether you're backing up a trailer, parking an RV, or navigating tight spaces with a delivery van, this heavy-duty system ensures full protection from obstacles up to 8 feet away! 📏\r\n\r\n✅ Seamless Installation: Four high-precision sensors are daisy-chained together for a simple, clean setup. Easily mount them on the rear, top, or bumper for optimal coverage! 🚙🔧\r\n✅ Loud & Clear Alerts: When an obstacle is detected, the system beeps progressively louder 📢—flatlining at 6 inches for maximum awareness!\r\n✅ Perfect for Fifth Wheels & Fleets: The included coiled cable 📡 stretches up to 10ft, allowing seamless connection between your truck and trailer 🚚\r\n✅ Camera Pass-Through Option: Integrate a rearview camera for a visual overlay with sensor readings, providing real-time distance markers on your screen! 🎥🖥\r\n✅ Premium USA-Based Support & Warranty: Every purchase includes a 30-day money-back guarantee 🔄 and a 1-year hassle-free replacement warranty 🛠.\r\n\r\n🔹 Get the best pricing & top-rated service – Order now from TadiBrothers! 🛒🚀",
          "isFeatured": false,
          "metaDescription": "Upgrade your vehicle’s safety with TadiBrothers' Commercial-Grade Parking Backup Sensors! ?? Perfect for trailers, vans, RVs & fleets, this heavy-duty system detects obstacles up to 8ft away with loud alerts & a camera pass-through option. USA-based support & best prici",
          "h1": "Commercial-Grade Parking Sensor System – Reliable Safety for RVs, Trailers & Vans",
          "canon": null,
          "enableCanon": null,
          "filter": "1,5",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        },
        {
          "id": 790,
          "title": "Premium FedEx Delivery Truck Camera Systemin 1080P AHD Full system with sensors",
          "youTubeCode": "-vFXmfFlk6M",
          "displayOrder": 0,
          "url": "FedEx-Delivery-Truck-Camera-Systemin-1080P-AHD-Full-system-with-sensors",
          "description": "Take a closer look at our Premium 1080P Delivery Van Camera System with Sensors (SKU69982)—designed specifically for FedEx trucks, Amazon vans, and commercial delivery fleets.\r\n\r\nIn this video, Tamir from TadiBrothers walks you through the full system setup, showing real-world footage of each component in action:\r\n\r\nBlinker-activated side cameras: Slim, aerodynamic design with built-in status indicators. These 1080P side cameras activate automatically when the turn signals are used, giving you real-time visibility during lane changes and turns.\r\n\r\n7-Inch Split-Screen AHD Monitor: See up to four cameras simultaneously with customizable view modes. Automatically reverts to your preferred layout after blinker or reverse functions.\r\n\r\n1080P Rear Camera: Automatically turns on when reversing or stays on continuously while driving for full-time rearview coverage.\r\n\r\nDaisy-chained parking sensor system: Includes eight sensors that run from rear to front, offering flexible mounting options for any vehicle type. Multiple installation styles are supported to make setup quick and simple.\r\n\r\nThis rugged, high-definition system is easy to install and built to handle the demands of daily delivery routes. Whether you manage a FedEx fleet, drive independently, or operate commercial vans, this camera setup adds safety, visibility,\r\nand peace of mind.\r\n\r\n✅ Easy to install\r\n✅ Weatherproof & built for daily routes\r\n✅ Perfect for FedEx, Amazon, and logistics vans",
          "isFeatured": false,
          "metaDescription": "Watch the 1080P delivery van camera system in action—built for FedEx and commercial fleets. Easy to install with blinker-activated side cameras, rearview, and 8 parking sensors. SKU69982. By TadiBrothers",
          "h1": "1080P Rear-View Camera System for FedEx Trucks – Rugged, Easy to Install, Built for Daily Delivery Routes",
          "canon": null,
          "enableCanon": null,
          "filter": "1,2",
          "emailInclude": false,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        }
      ]
    },
     {
      "orderItemId": 92244,
      "productId": 3246,
      "quantity": 5,
      "productIsParent": null,
      "protectionPlanProduct": 2,
      "protectionPlanProductPrice": 190,
      "cartOptionId": null,
      "productPrice": 299.99,
      "productName": "Delivery Truck 1080P Digital Wireless Camera System with 3 Cameras (V3)",
      "sku": "SKU15883",
      "isMainProduct": true,
      "defaultImage": "638452490207005553.jpg",
      "category": {
        "categoryId": 146,
        "categoryName": "FedEx Vehicles"
      },
      "components": [
        {
          "componentProductId": 2580,
          "componentSKU": "SKU18392",
          "componentName": "7-Inch Digital Wireless Rear View Monitor, Commercial Grade (V3)",
          "componentPrice": 149.99,
          "componentDefaultImage": "638324408437490723.jpg",
          "componentUniqueName": "digital-wireless-7-inch-lcd-rear-view-monitor-v3",
          "componentListPrice": 279.99,
          "componentAverageRating": 4.5,
          "componentNumberOfRatings": 72
        },
        {
          "componentProductId": 3181,
          "componentSKU": "SKU34190",
          "componentName": "1080P Digital Wireless RV Backup Camera with 300ft Range (V3)",
          "componentPrice": 399.99,
          "componentDefaultImage": "638326198169745058.jpg",
          "componentUniqueName": "digital-wireless-rv-backup-camera-300ft-range-v3",
          "componentListPrice": 479.99,
          "componentAverageRating": 4.6,
          "componentNumberOfRatings": 35
        },
        {
          "componentProductId": 3696,
          "componentSKU": "SKU52561",
          "componentName": "2 Digital Wireless Premium 1080P Side Cameras with Driver and Passenger sides 2025 (V3)",
          "componentPrice": 574.99,
          "componentDefaultImage": "638687312255960489.jpg",
          "componentUniqueName": "2-Digital-built-in-premium-side-rv-camera-wireless-v3-2025",
          "componentListPrice": 749.99,
          "componentAverageRating": 4.56666666666667,
          "componentNumberOfRatings": 30
        }
      ],
      "options": [
        {
          "optionId": 6656,
          "optionsCategoryId": 631,
          "optionSKU": "SKU18392",
          "optionName": "7-Inch Digital Monitor DVR V3 (SKU18392U)",
          "optionPrice": 224.99,
          "optionImage": "7-inch_Digital_DVR_V3.png",
          "optionDefaultImage": "638452490207005553.jpg"
        },
        {
          "optionId": 6656,
          "optionsCategoryId": 631,
          "optionSKU": "SKU18392",
          "optionName": "7-Inch Digital Monitor DVR V3 (SKU18392U)",
          "optionPrice": 124.99,
          "optionImage": "7-inch_Digital_DVR_V3.png",
          "optionDefaultImage": "638452490207005553.jpg"
        }
      ],
      "videos": [
        {
          "id": 639,
          "title": "How to Pair TadiBrothers Version 3 Digital Wireless Cameras – Step-by-Step Guide",
          "youTubeCode": "Pasej8IIkp0",
          "displayOrder": 6,
          "url": "Pairing-Digital-Wireless-Camera-(V3)",
          "description": "In this comprehensive video tutorial, Tamir from TadiBrothers walks you through the step-by-step process of pairing the new Version 3 Digital Wireless Cameras. With upgraded features like integrated DVRs, square buttons, and blue plungers for pairing, these cameras are designed for maximum efficiency. \r\n\r\nLearn how to connect the antenna, power up your monitor using a 12V connection, and pair your cameras to the desired channels. Tamir explains both the shortcut and menu-based pairing methods, making it simple for you to get your RV, license, or side cameras up and running.\r\n\r\nYou’ll discover helpful tips, like identifying indicator lights to confirm power and using the split-screen mode to view multiple cameras simultaneously. Plus, Tamir provides troubleshooting advice and a quick overview of the mute function to eliminate microphone feedback. Whether you’re a first-time user or upgrading from a previous version, this video ensures a seamless setup experience.\r\n\r\nFor personalized support, TadiBrothers’ U.S.-based tech team is just a call away at 866-966-5550. Watch now and see how easy it is to pair your Version 3 wireless cameras!",
          "isFeatured": false,
          "metaDescription": "Learn how to pair TadiBrothers Version 3 Wireless Cameras with this step-by-step video guide. Features include DVRs, split-screen mode & expert tips. Call 866-966-5550 for support!",
          "h1": "Pairing TadiBrothers Version 3 Wireless Cameras Made Easy",
          "canon": null,
          "enableCanon": null,
          "filter": "5,6,7,9",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        },
        {
          "id": 640,
          "title": "Master Split Screen Settings on TadiBrothers Digital 3 Systems | Expert Guide",
          "youTubeCode": "5FdVw9Hgu78",
          "displayOrder": 6,
          "url": "Split-screen-setting-for-the-Digital-backup-camera-By-TadiBrothers-(V3)",
          "description": "Welcome to TadiBrothers! In this video, Tamir walks you through the split-screen settings for the Digital 3 version of our systems, helping you achieve the perfect camera view for your needs. If your system features a blue cube or plunger on the camera, you’re in the right place!\r\n\r\nTamir demonstrates how to customize your split-screen views by accessing the menu and selecting different modes. Learn how to set up your channels for 3-camera or 4-camera configurations and discover features like the HV view, quad view, and side-by-side layouts. Whether you’re pairing new cameras or optimizing your existing setup, this step-by-step guide ensures you get the most out of your TadiBrothers system.\r\n\r\nThis tutorial highlights the flexibility and user-friendly design of our backup camera systems, empowering you to adjust your views to suit any scenario. Have questions? Our U.S.-based support team is here for you at 866-966-5550, and Tamir himself is happy to assist.\r\n\r\nSubscribe for more helpful guides from TadiBrothers—where “we back you up” with innovative solutions and unbeatable customer service!",
          "isFeatured": false,
          "metaDescription": "Learn how to customize split-screen settings on the TadiBrothers Digital 3 system. Watch step-by-step instructions and optimize your camera views. Call 866-966-5550 for support!",
          "h1": "How to Customize Split Screen Settings on Your TadiBrothers Digital 3 System",
          "canon": null,
          "enableCanon": null,
          "filter": "5,6,7,9",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        },
        {
          "id": 641,
          "title": "Complete Guide to Mobile DVR Settings for TadiBrothers Digital Wireless System V3",
          "youTubeCode": "rETWJ-II7x0",
          "displayOrder": 6,
          "url": "Mobile-DVR-Setting-and-Playback-for-the-Digital-Wireless-Backup-Cameras-System-by-TadiBrothers-(V3)",
          "description": "In this comprehensive guide, Tamir from TadiBrothers walks you through the settings and features of the Mobile DVR included in the Digital Wireless System V3. Identified by the blue square on the monitor, RV camera, and license camera, this system is designed for seamless recording and playback. Learn how to check DVR modes, install and format SD cards, and activate loop recording, ensuring your system continuously overwrites old recordings to save space.\r\n\r\nTamir also explains how to customize recording intervals (1, 3, or 5 minutes) and highlights the system’s unique ability to record each channel individually. This allows for detailed event tracking, whether you're reviewing footage from an RV, side, or license camera.\r\n\r\nPlayback options are versatile—you can view recordings directly on the monitor or extract the memory stick to a computer. The guide also provides troubleshooting tips and ensures users get the most out of their Mobile DVR.\r\n\r\nFor further assistance, the TadiBrothers American-based tech team is available at 866-966-5550. With these easy steps, you’ll master the features of your Digital Wireless System V3 and enjoy peace of mind on every journey. \"We back you up!\"\r\n\r\nLet me know if you'd like any adjustments or additional elements!",
          "isFeatured": false,
          "metaDescription": "Step-by-step guide to setting up your TadiBrothers Mobile DVR on the Digital Wireless System V3. Learn about loop recording, formatting SD cards, and playback features.",
          "h1": "How to Use and Optimize Your Mobile DVR on TadiBrothers Digital Wireless System V3",
          "canon": null,
          "enableCanon": null,
          "filter": "5,6,7,9",
          "emailInclude": true,
          "averageRating": null,
          "numberOfRatings": null,
          "lowas": null
        }
      ]
    }
  ]
}